### ISSUE TITLE
Consider adding the sphinx-extension GitHub topic

### ISSUE THREAD

**Issue by jdillard** [webknjaz/intersphinx-untangled#2]
I just wanted to say you should consider adding the `sphinx-extension` topic, https://github.com/topics/sphinx-extension, to the repo so it is easier for others to find on the GitHub ecosystem (I had a hard time re-finding this one). There are currently 143 other sphinx extensions that use that topic.

**Comment by webknjaz** [comment]
Strictly speaking, this is not an extension, though. Just a static website. But alright, I've added a few more topics.

**Comment by jdillard** [comment]
Doh, I should have looked at the code. I just saw you had some extension topics already.
