### ISSUE TITLE
`:py:module` should be `:py:mod`?

### ISSUE THREAD

**Issue by astrojuanlu** [webknjaz/intersphinx-untangled#6]
I tried adding a

```
:py:module:`sphinx.ext.githubpages`
```

role to my documentation and I got:

```
WARNING: Unknown interpreted text role "py:module".
```

However, replacing it by

```
:py:mod:`sphinx.ext.githubpages`
```

did the trick.

**Comment by webknjaz** [comment]
Interesting. Looks like it. Wanna send a PR?


https://github.com/webknjaz/intersphinx-untangled/blob/79a4f4f/templates/table.html.j2#L32
